#!/bin/bash
ip link set dev eth0 up
ip a a 1.2.3.34/27 dev eth0

ip link set dev eth1 up
ip a a 1.2.3.17/28 dev eth1

#echo 1 > /proc/sys/net/ipv4/ip_forward 

#ip route add 192.168.111.128/25 via 1.2.3.33
#ip route add 1.2.3.128/25 via 1.2.3.33
#ip route add 1.2.3.64/26 via 1.2.3.33

service quagga start

#Filtrage
#Tout refuser
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
#Accepter les ping ICMP
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT
# Accepter le routage RIP
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT
#Accepter le DNS
iptables -t filter -A FORWARD -d 1.2.3.19/28 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 1.2.3.19/28 -p udp --sport 53 -j ACCEPT
#Accepter le WEB
iptables -t filter -A FORWARD -d 1.2.3.20/28 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 1.2.3.20/28 -p tcp --sport 80 -j ACCEPT
# Accepter le FRP
iptables -A FORWARD -d 1.2.3.21/28 -p tcp --dport 21 -j ACCEPT
iptables -A FORWARD -s 1.2.3.21/28 -p tcp --sport 21 -j ACCEPT
iptables -A FORWARD -p tcp --sport 1024: --dport 1024: -j ACCEPT
