#!/bin/bash
ip link set dev eth0 up
ip a a 1.2.3.21/28 dev eth0

#ROUTAGE STATIQUE
#ip route add 192.168.111.128/25 via 1.2.3.17
#ip route add 1.2.3.128/25 via 1.2.3.17
#ip route add 1.2.3.64/26 via 1.2.3.17
#ip route add 1.2.3.32/27 via 1.2.3.17

ip route add default via 1.2.3.17

# Créer un nouvel utilisateur
useradd ys
echo "ys:ys" | chpasswd
mkdir /home/ys

# Etablir ys en tant que propriétaire
chown ys /home/ys
usermod --shell /bin/bash ys

hostname FTP
echo "1.2.3.21 FTP" >> /etc/hosts

# Désactiver le mode world-writable
chmod o-w /etc/proftpd/ etc/proftpd/modules.conf etc/proftpd/proftpd.conf 

# Démarrer le serveur FTP
service proftpd start
