#!/bin/bash
ip link set dev eth0 up
ip a a 1.2.3.66/26 dev eth0

ip link set dev eth1 up
ip a a 1.2.3.33/27 dev eth1

#ROUTAGE STATIQUE
#echo 1 > /proc/sys/net/ipv4/ip_forward 

#ip route add 192.168.111.128/25 via 1.2.3.65
#ip route add 1.2.3.128/25 via 1.2.3.65
#ip route add 1.2.3.16/28 via 1.2.3.34

service quagga start
